version: "3"
services: 
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    # mapear os dados do meu local e do docker para não perder os dados quando a imagem for reiniciada
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api_container
    # executa o Dockerfile
    image: node:12
    working_dir: /usr/src/clean-node-api
    # nome da imagem
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    volumes:
      # NOTE - "/" no final diz pro docker para atualizar os arquivos da pasta
      - ./dist/:/usr/src/clean-node-api/dist/
      - ./package.json:/usr/src/clean-node-api/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo
